// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsqtm9ZTOItav0VPUbjJ2hGXliN3-mlQ',
    appId: '1:165358649281:web:deadb1b80f48405af67940',
    messagingSenderId: '165358649281',
    projectId: 'test3-daafc',
    authDomain: 'test3-daafc.firebaseapp.com',
    storageBucket: 'test3-daafc.appspot.com',
    measurementId: 'G-QWLFYD049E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFDOrdBbyEpl-kj9KwSZ-ubzZKn5g74U',
    appId: '1:165358649281:android:732f468edadc69a8f67940',
    messagingSenderId: '165358649281',
    projectId: 'test3-daafc',
    storageBucket: 'test3-daafc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9305NrZ5cEz9ASjjH75FhsGlOMP2abO0',
    appId: '1:165358649281:ios:1d1c6eb4ea601a1ff67940',
    messagingSenderId: '165358649281',
    projectId: 'test3-daafc',
    storageBucket: 'test3-daafc.appspot.com',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9305NrZ5cEz9ASjjH75FhsGlOMP2abO0',
    appId: '1:165358649281:ios:1d1c6eb4ea601a1ff67940',
    messagingSenderId: '165358649281',
    projectId: 'test3-daafc',
    storageBucket: 'test3-daafc.appspot.com',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjsqtm9ZTOItav0VPUbjJ2hGXliN3-mlQ',
    appId: '1:165358649281:web:6d17587b696c7ab7f67940',
    messagingSenderId: '165358649281',
    projectId: 'test3-daafc',
    authDomain: 'test3-daafc.firebaseapp.com',
    storageBucket: 'test3-daafc.appspot.com',
    measurementId: 'G-YB16QD5WV6',
  );
}
